[package]
name = "rustout"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.29.0"
egui = "0.29.0"
egui_extras = {version = "0.29.1", features = ["image"]}
image = { version = "0.25", default-features = false, features = ["png"] }
